"""
Global configuration variables for the CS GO application.

This module centralizes all configuration constants used across the application,
including API endpoints, default values, and other global settings.
"""

# API Configuration
BASE_URL = "https://cs-go-production.up.railway.app"
WS_URL = "wss://cs-go-production.up.railway.app/ws"

# Application Settings
APP_NAME = "CS Go"
APP_VERSION = "1.0.0"

# Default Values
DEFAULT_BOARD_SIZE = 19
DEFAULT_VOLUME = 50

# 100 random animals nouns, 100 adjectives for local usernames
# Format: adjectives = [(masculin, féminin), ...]
# Format: nouns = [(nom, genre), ...] where genre is 0 or 1
LOCAL_USERNAMES = {
    "adjectives": [
        ("Agile", "Agile"),
        ("Brave", "Brave"),
        ("Malin", "Maligne"),
        ("Sage", "Sage"),
        ("Vif", "Vive"),
        ("Fier", "Fière"),
        ("Loyal", "Loyale"),
        ("Noble", "Noble"),
        ("Serein", "Sereine"),
        ("Vaillant", "Vaillante"),
        ("Rusé", "Rusée"),
        ("Puissant", "Puissante"),
        ("Rapide", "Rapide"),
        ("Discret", "Discrète"),
        ("Féroce", "Féroce"),
        ("Gracieux", "Gracieuse"),
        ("Habile", "Habile"),
        ("Intrépide", "Intrépide"),
        ("Jovial", "Joviale"),
        ("Astucieux", "Astucieuse"),
        ("Audacieux", "Audacieuse"),
        ("Brillant", "Brillante"),
        ("Calme", "Calme"),
        ("Déterminé", "Déterminée"),
        ("Élégant", "Élégante"),
        ("Fort", "Forte"),
        ("Généreux", "Généreuse"),
        ("Hardi", "Hardie"),
        ("Imaginatif", "Imaginative"),
        ("Juste", "Juste"),
        ("Lumineux", "Lumineuse"),
        ("Mystérieux", "Mystérieuse"),
        ("Nouveau", "Nouvelle"),
        ("Optimiste", "Optimiste"),
        ("Patient", "Patiente"),
        ("Quiet", "Quiete"),
        ("Radieux", "Radieuse"),
        ("Solide", "Solide"),
        ("Tenace", "Tenace"),
        ("Unique", "Unique"),
        ("Vigilant", "Vigilante"),
        ("Sage", "Sage"),
        ("Zélé", "Zélée"),
        ("Affûté", "Affûtée"),
        ("Bienveillant", "Bienveillante"),
        ("Courageux", "Courageuse"),
        ("Doux", "Douce"),
        ("Énergique", "Énergique"),
        ("Fringant", "Fringante"),
        ("Gentil", "Gentille"),
        ("Héroïque", "Héroïque"),
        ("Ingénieux", "Ingénieuse"),
        ("Joyeux", "Joyeuse"),
        ("Légendaire", "Légendaire"),
        ("Majestueux", "Majestueuse"),
        ("Nerveux", "Nerveuse"),
        ("Observateur", "Observatrice"),
        ("Preste", "Preste"),
        ("Quieto", "Quieta"),
        ("Robuste", "Robuste"),
        ("Souple", "Souple"),
        ("Téméraire", "Téméraire"),
        ("Uni", "Unie"),
        ("Vénérable", "Vénérable"),
        ("Zelé", "Zelée"),
        ("Adroit", "Adroite"),
        ("Beau", "Belle"),
        ("Charmant", "Charmante"),
        ("Dynamique", "Dynamique"),
        ("Espiègle", "Espiègle"),
        ("Farouche", "Farouche"),
        ("Glorieux", "Glorieuse"),
        ("Honnête", "Honnête"),
        ("Illustre", "Illustre"),
        ("Joli", "Jolie"),
        ("Libre", "Libre"),
        ("Magnifique", "Magnifique"),
        ("Nonchalant", "Nonchalante"),
        ("Orgueilleux", "Orgueilleuse"),
        ("Paisible", "Paisible"),
        ("Rayonnant", "Rayonnante"),
        ("Sincère", "Sincère"),
        ("Tranquille", "Tranquille"),
        ("Valeureux", "Valeureuse"),
        ("Zen", "Zen"),
        ("Alerte", "Alerte"),
        ("Bon", "Bonne"),
        ("Chaleureux", "Chaleureuse"),
        ("Digne", "Digne"),
        ("Éveillé", "Éveillée"),
        ("Flamboyant", "Flamboyante"),
        ("Gourmand", "Gourmande"),
        ("Harmonieux", "Harmonieuse"),
        ("Indomptable", "Indomptable"),
        ("Jeune", "Jeune"),
        ("Luminescent", "Luminescente"),
        ("Merveilleux", "Merveilleuse"),
        ("Nocturne", "Nocturne"),
        ("Olympien", "Olympienne"),
        ("Prudent", "Prudente"),
    ],
    "nouns": [
        ("Renard", 0),
        ("Louve", 1),
        ("Ours", 0),
        ("Aigle", 0),
        ("Faucon", 0),
        ("Tigre", 0),
        ("Lion", 0),
        ("Panthère", 1),
        ("Cerf", 0),
        ("Hibou", 0),
        ("Lynx", 0),
        ("Puma", 0),
        ("Jaguar", 0),
        ("Léopard", 0),
        ("Guépard", 0),
        ("Coyote", 0),
        ("Chacal", 0),
        ("Bison", 0),
        ("Élan", 0),
        ("Renne", 0),
        ("Castor", 0),
        ("Loutre", 1),
        ("Blaireau", 0),
        ("Martre", 1),
        ("Belette", 1),
        ("Hermine", 1),
        ("Furet", 0),
        ("Putois", 0),
        ("Vison", 0),
        ("Raton", 0),
        ("Écureuil", 0),
        ("Tamia", 0),
        ("Marmotte", 1),
        ("Porc-épic", 0),
        ("Hérisson", 0),
        ("Taupe", 1),
        ("Musaraigne", 1),
        ("Chauve-souris", 1),
        ("Corbeau", 0),
        ("Corneille", 1),
        ("Pie", 1),
        ("Geai", 0),
        ("Merle", 0),
        ("Grive", 1),
        ("Rouge-gorge", 0),
        ("Mésange", 1),
        ("Sittelle", 1),
        ("Grimpereau", 0),
        ("Pic", 0),
        ("Martin-pêcheur", 0),
        ("Héron", 0),
        ("Cigogne", 1),
        ("Flamant", 0),
        ("Pélican", 0),
        ("Cormoran", 0),
        ("Mouette", 1),
        ("Goéland", 0),
        ("Sterne", 1),
        ("Fou", 0),
        ("Albatros", 0),
        ("Pétrel", 0),
        ("Macareux", 0),
        ("Pingouin", 0),
        ("Manchot", 0),
        ("Phoque", 0),
        ("Morse", 0),
        ("Dauphin", 0),
        ("Orque", 1),
        ("Baleine", 1),
        ("Requin", 0),
        ("Raie", 1),
        ("Tortue", 1),
        ("Crocodile", 0),
        ("Alligator", 0),
        ("Caïman", 0),
        ("Iguane", 0),
        ("Varan", 0),
        ("Gecko", 0),
        ("Caméléon", 0),
        ("Serpent", 0),
        ("Cobra", 0),
        ("Vipère", 1),
        ("Python", 0),
        ("Anaconda", 0),
        ("Boa", 0),
        ("Salamandre", 1),
        ("Triton", 0),
        ("Grenouille", 1),
        ("Crapaud", 0),
        ("Rainette", 1),
        ("Panda", 0),
        ("Koala", 0),
        ("Kangourou", 0),
        ("Wallaby", 0),
        ("Wombat", 0),
        ("Tasmanie", 1),
        ("Émeu", 0),
        ("Autruche", 1),
        ("Kiwi", 0),
        ("Condor", 0),
    ],
}
